export const skills = {
  "Data Science & ML": [
    "Python",
    "NumPy",
    "Pandas",
    "Scikit-learn",
    "Data Cleaning",
    "SQL",
    "R",
    "Data Mining",
    "Data Modeling",
    "ETL",
    "ELT",
    "NLP",
    "Statistical Analysis",
  ],
  "Visualization & BI": [
    "Tableau",
    "Power BI",
    "Data Visualization",
    "Excel",
    "Matplotlib",
    "Seaborn",
    "Plotly",
  ],
  "Cloud & Infrastructure": [
    "AWS",
    "AWS S3",
    "AWS Glue",
    "AWS Redshift",
    "AWS SageMaker",
    "Azure",
    "Snowflake",
    "Databricks",
    "Docker",
    "Git",
    "Github",
  ],
  "Business & Strategy": [
    "Business Intelligence",
    "Data Analytics",
    "Project Management",
    "Agile",
    "SDLC",
    "Business Analysis",
    "Financial Forecasting",
    "AI Strategy",
    "Product Development",
    "Automation",
    "AI agents",
  ],
  "AI & Automation": [
    "AI",
    "Machine Learning",
    "Predictive Modeling",
    "Recommendation Systems",
    "n8n",
    "A2A Protocol",
    "Product Analytics",
    "Marketing Analytics",
  ],
  "Web & Development": ["HTML", "CSS", "JavaScript", "Node.js", "MongoDB", "Linux", "API Development"],
  "Media & AV": ["Live Audio", "AV Technology", "Audio Engineering", "Acoustics","Sound Design" ],
}
